DefenceStore/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DefenceStore.Models
{
    public class Order
    {
		[Key][Required]
		public int ID { get; set; }

        [Required][ForeignKey("Customer")]
		public int CustomerID { get; set; }
        public virtual Customer Customer { get; set; }

        [DataType(DataType.Currency)][Required]
		public string BillingType { get; set; }

        [Required]
		public string Address { get; set; }

        [DataType(DataType.DateTime)][Required]
		public DateTime Date { get; set; }

        public string Desciption { get; set; }

        [Required]
        public float TotalBill { get; set; }

        public List<OrderProduct> products { get; set; }
    }
}

DefenceStore/Controllers/OrderProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DefenceStore.DAL;
using DefenceStore.Models;

namespace DefenceStore.Controllers
{
    public class OrderProductsController : Controller
    {
        private DefenceStoreContext db = new DefenceStoreContext();

        // GET: OrderProducts
        public ActionResult Index()
        {
            var orderProducts = db.OrderProducts.Include(o => o.Order).Include(o => o.Product);
            return View(orderProducts.ToList());
        }

        // GET: OrderProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }
            return View(orderProduct);
        }

        // GET: OrderProducts/Details/5
        public ActionResult Search(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var orderProduct = db.OrderProducts.Where( op => op.OrderID == id).Include(op => op.Product).Include(op => op.Order).AsEnumerable();
            
            if (orderProduct == null || orderProduct.Count() < 1)
            {
                return HttpNotFound();
            }
            return PartialView(orderProduct);
        }

        // GET: OrderProducts/Details/5
        public ActionResult SearchEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var orderProduct = db.OrderProducts.Where(op => op.OrderID == id).Include(op => op.Product).Include(op => op.Order).AsEnumerable();

            if (orderProduct == null || orderProduct.Count() < 1)
            {
                return HttpNotFound();
            }
            return PartialView(orderProduct);
        }

        // GET: OrderProducts/Create
        public ActionResult Create()
        {
            ViewBag.OrderID = new SelectList(db.Orders, "ID", "BillingType");
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name");
            return View();
        }

        // POST: OrderProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,OrderID,ProductID")] OrderProduct orderProduct)
        {
            if (ModelState.IsValid)
            {
                db.OrderProducts.Add(orderProduct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrderID = new SelectList(db.Orders, "ID", "BillingType", orderProduct.OrderID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", orderProduct.ProductID);
            return View(orderProduct);
        }

        // GET: OrderProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrderID = new SelectList(db.Orders, "ID", "BillingType", orderProduct.OrderID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", orderProduct.ProductID);
            return View(orderProduct);
        }

        // POST: OrderProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,OrderID,ProductID")] OrderProduct orderProduct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(orderProduct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OrderID = new SelectList(db.Orders, "ID", "BillingType", orderProduct.OrderID);
            ViewBag.ProductID = new SelectList(db.Products, "ID", "Name", orderProduct.ProductID);
            return View(orderProduct);
        }

        // GET: OrderProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            if (orderProduct == null)
            {
                return HttpNotFound();
            }

            return View(orderProduct);
        }

        // POST: OrderProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderProduct orderProduct = db.OrderProducts.Find(id);
            orderProduct.Order.TotalBill -= orderProduct.Quantity * orderProduct.Product.Price;
            db.OrderProducts.Remove(orderProduct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

DefenceStore/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DefenceStore.DAL;
using DefenceStore.Models;
using DefenceStore.ViewModels;
using System.Collections;

namespace DefenceStore.Controllers
{
    public class OrdersController : Controller
    {
        private DefenceStoreContext db = new DefenceStoreContext();

        // GET: Orders
        public ActionResult Index()
        {
            if (Session["Customer"] == null)
            {
                return View(new List<Order>());
            }

            Customer customer = Session["Customer"] as Customer;
            List<Order> orders;

            if (customer.IsAdmin)
            {
                orders = db.Orders.Include(o => o.Customer).ToList();
            }
            else
            {
                orders = db.Orders.Include(o => o.Customer).Where(o => o.CustomerID == customer.ID).ToList();
            }


            foreach (Order o in orders)
            {
                float res = calculateTotalBill(o);
            }

            db.SaveChanges();
            return View(orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        public ActionResult UserNotFound()
        {
            return View();
        }

        public ActionResult EmptyCart()
        {
            return View();
        }

        public ActionResult CreateOrder()
        {
            if (Session["Customer"] == null)
            {
                return Redirect("UserNotFound");
            }
            int? cid = (Session["Customer"] as Customer).ID;
            List<Product> products = Session["Products"] as List<Product>;

            if (products == null || products.Count < 1)
            {
                return Redirect("EmptyCart");
            }

            Order order = new Order();
            order.CustomerID = cid.Value;
            order.Customer = db.Customers.Find(cid);

            var UserOrders = db.Orders.Where(o => o.CustomerID == cid.Value).ToList<Order>();

            if (UserOrders.Count > 0)
            {               
                order.BillingType = UserOrders[UserOrders.Count - 1].BillingType;
                order.Address = UserOrders[UserOrders.Count - 1].Address;
            }

            order.Date = DateTime.Now;
            order.products = new List<OrderProduct>();

            foreach (Product prod in products)
            {
                order.products.Add(new OrderProduct
                {
                    Product = prod,
                    ProductID = prod.ID,
                    Order = order,
                    OrderID = order.ID,
                    Quantity = 1
                });
            }


            if ((Session["Customer"] as Customer).IsAdmin)
                ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName");
            else
                ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName").Where(c => c.Value == cid.Value.ToString());

            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrder(Order order)
        {
            if (isValid(order))
            {
                if (order.Desciption == null)
                    order.Desciption = "";

                order.Customer = db.Customers.Find(order.CustomerID);

                foreach (OrderProduct p in order.products)
                {
                    var product = db.Products.Find(p.ProductID);
                    p.Product = product;
                    order.TotalBill += p.Product.Price * p.Quantity;
                }
                List<OrderProduct> op = order.products;
                order.products = null;

                if (ModelState.IsValid)
                {
                    db.Orders.Add(order);
                    db.SaveChanges();
                }


                for (int i = 0; i < op.Count; i++)
                {
                    op[i].Order = order;
                    op[i].OrderID = order.ID;
                }

                db.OrderProducts.AddRange(op);

                db.SaveChanges();

                Session.Remove("Products");
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName");
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CustomerID,BillingType,Address,Date,Desciption,TotalBill")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", order.CustomerID);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", order.CustomerID);
            order.products = db.OrderProducts.Where(op => op.OrderID == order.ID).ToList();
            calculateTotalBill(order);
            return View(order);
        }

        private bool isValid(Order order)
        {
            if (order.Address == string.Empty || order.BillingType == string.Empty)
                return false;

            foreach (OrderProduct op in order.products)
            {
                var p = db.Products.Find(op.ProductID);
                if (op.Quantity < 1 || p.Price < 1 /*|| op.Quantity > p.QuantityInStock*/)
                    return false;
            }

            return true;
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order)
        {
            if (isValid(order))
            {
                order.Customer = db.Customers.Find(order.CustomerID);

                var ops = db.OrderProducts.Where(op => order.ID == op.OrderID);
                foreach (var cop in order.products)
                {
                    OrderProduct top = ops.Where(op => op.ID == cop.ID).First();
                    top.Quantity = cop.Quantity;
                }

                calculateTotalBill(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", order.CustomerID);

            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            calculateTotalBill(order);
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.OrderProducts.RemoveRange(db.OrderProducts.Where(op => op.OrderID == order.ID));
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Graphs(int? id)
        {
            return View("Graphs");
        }

        protected float calculateTotalBill(Order order)
        {
            var orders = db.Orders.Include(o => o.Customer);
            var order_prd = db.OrderProducts.Include(o => o.Product).Include(o => o.Order);

            /* 
                SELECT dbo.Orders.ID, dbo.Products.Desciption, dbo.OrderProducts.ID
                FROM dbo.Orders 
	                JOIN dbo.OrderProducts ON dbo.Orders.ID = dbo.OrderProducts.OrderID 
	                JOIN dbo.Products ON dbo.OrderProducts.ProductID = dbo.Products.ID 
             */

            var q = (from ords in orders
                     join ord_p in order_prd on ords.ID equals ord_p.OrderID
                     join prd in db.Products on ord_p.ProductID equals prd.ID
                     select new { ords.ID, prd.Price, OPID = ord_p.ID });

            order.TotalBill = 0;

DefenceStore/Views/Orders/CreateOrder.cshtml
@model DefenceStore.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
            </div>
        </div>
        <table class="table" id="products-table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.products.FirstOrDefault().OrderID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.products.FirstOrDefault().Product.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.products.FirstOrDefault().Product.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.products.FirstOrDefault().Quantity)
                </th>
                <th> Total Price</th>
                <th></th>
            </tr>
            @for (int i = 0; i < Model.products.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.products[i].OrderID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model.products[i].Product.Name)
                        @Html.HiddenFor(model => Model.products[i].ProductID)
                    </td>
                    <td>
                        <div id="@("Price-" + i.ToString())">
                            @Html.DisplayFor(modelItem => Model.products[i].Product.Price)
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.EditorFor(modelItem => Model.products[i].Quantity, new { htmlAttributes = new { @class = "form-control", max = 20, min = 0, id = "Quantity-" + i.ToString() } })
                                @Html.ValidationMessageFor(modelItem => Model.products[i].Quantity, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                    <td>
                        <div id="@("TotalPrice-" + i.ToString())">
                            @(Model.products[i].Quantity * Model.products[i].Product.Price)
                        </div>
                    </td>
                    <td>
                        @Html.ActionLink("Remove", "Delete", "OrderProducts", new { Model.products[i].ID }, null)
                    </td>
                </tr>
            }
        </table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<br />
<h4 id="sum-total">Total: @Html.DisplayFor(modelItem => Model.TotalBill) </h4>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    function updateTotal() {
        var totalPrice = 0;
        $("#products-table").find('.form-control').each(function () {
            var curr_form = "#" + $(this).attr('id');
            var form_number = curr_form.substring(curr_form.length - 1, curr_form.length);
            var quantity = $(curr_form).val();
            var price = parseFloat($("#Price-" + form_number).text());
            totalPrice += price * quantity;
        });

        $("#sum-total").text("Total: " + totalPrice);
    }
    updateTotal();
    $("#products-table").find('.form-control').each(function () {
        var curr_form = "#" + $(this).attr('id');
        var form_number = curr_form.substring(curr_form.length - 1, curr_form.length);
        $(curr_form).click(function () {
            var quantity = $(curr_form).val();
            var price = parseFloat($("#Price-" + form_number).text());
            $("#TotalPrice-" + form_number).text(price * quantity);
            updateTotal();
        });
    });

</script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DefenceStore/Views/Orders/Delete.cshtml
@model DefenceStore.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desciption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desciption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalBill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalBill)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DefenceStore/Views/Orders/Details.cshtml
@model DefenceStore.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desciption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desciption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalBill)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalBill)
        </dd>
    </dl>
</div>
<div>
    @{ Html.RenderAction("Search", "OrderProducts", Model.ID); }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DefenceStore/Views/Orders/EmptyCart.cshtml
@{
    ViewBag.Title = "Cart is empty!";
}

<h2>העגלה ריקה</h2>
<div>
    לא ניתן לבצע פעולות הזמנה ללא בחירת מוצרים מהחנות, אנא בחר מוצרים מעמוד המוצרים שלנו.
    <br />
    <h4>@Html.ActionLink("לעמוד המוצרים", "Index", "Products")</h4>
</div>

DefenceStore/Views/Orders/Index.cshtml
@model IEnumerable<DefenceStore.Models.Order>
    @{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "CreateOrder")
    </p>


@using (Html.BeginForm("Search", "Orders", FormMethod.Get))
{
    <p>
        Name: @Html.TextBox("name")
        <input type="submit" value="Filter" />
    </p>
}



    <table class="table">
        <tr>
            <th> Name </th>
            <th> Payment Method </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desciption)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalBill)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.FirstName)
                    @Html.DisplayFor(modelItem => item.Customer.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BillingType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desciption)
                </td>
                <td>
                    @Html.ActionLink(item.TotalBill.ToString(), "Search", "OrderProducts", new { item.ID }, null)
                </td>
                <td>
                    @{
                        if (Session["Customer"] != null && ((DefenceStore.Models.Customer)Session["Customer"]).IsAdmin)
                        {
                            @Html.ActionLink(".", "Edit", new { id = item.ID }, new { @class = "edit" });
                        }
                    }
                    @Html.ActionLink(".", "Details", new { id = item.ID }, new { @class = "details" })
                    @Html.ActionLink(".", "Delete", new { id = item.ID }, new { @class = "delete" })
                </td>
                </tr>
        }
    </table>

DefenceStore/Views/Orders/Search.cshtml
@model IEnumerable<DefenceStore.Models.Order>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@using (Html.BeginForm("Search", "Orders", FormMethod.Get))
{
    <p>
        Name: @Html.TextBox("name")
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Payment Method
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Desciption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalBill)
        </th>
        <th></th>
    </tr>

@if (Model.Any())
{
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.FirstName)
                @Html.DisplayFor(modelItem => item.Customer.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desciption)
            </td>
            <td>
                @Html.ActionLink(item.TotalBill.ToString(), "Search", "OrderProducts", new { item.ID }, null)
            </td>
            <td>
                @{
                    if (Session["Customer"] != null && ((DefenceStore.Models.Customer)Session["Customer"]).IsAdmin)
                    {
                        @Html.ActionLink(".", "Edit", new { id = item.ID }, new { @class = "edit" });
                    }
                }
                @Html.ActionLink(".", "Details", new { id = item.ID }, new { @class = "details" })
                @Html.ActionLink(".", "Delete", new { id = item.ID }, new { @class = "delete" })
            </td>
        </tr>
     }
}
else
{
    <tr>
        <td>
            No Results Found!
        </td>
    </tr>
}

</table>

DefenceStore/Views/Orders/UserNotFound.cshtml
@{
    ViewBag.Title = "User not found!";
}

<h2>לא זוהה משתמש</h2>
<div>
    לא ניתן לבצע פעולות הזמנה ללא התחברות למערכת, אנא 
    @Html.ActionLink("התחבר", "CustLogin", "Customers")
    <br/>
    במקרה ואת\ה מחובר אנא פנה לתמיכה.
</div>