DefenceStore/Models/Manufactor.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DefenceStore.Models
{
    public class Manufactor
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }
        public string Desciption { get; set; }
        public int TotalProduct { get; set; }

        [DataType(DataType.ImageUrl)]
        public string Logo { get; set; }
    }
}

DefenceStore/Controllers/ManufactorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DefenceStore.DAL;
using DefenceStore.Models;
using System.Reflection;

namespace DefenceStore.Controllers
{
    public class ManufactorsController : Controller
    {
        private DefenceStoreContext db = new DefenceStoreContext();

        public object TypeUtils { get; private set; }

        // GET: Manufactors
        public ActionResult Index()
        {
            /*
             -------------------------------------------
             SQL Syntax:
             -------------------------------------------
             SELECT name, count(name) FROM people
             GROUP by name 
             
            -------------------------------------------
            Linq Method 1:
            -------------------------------------------
            var query = from p in context.People
            group p by p.name into g
            select new
            {
              name = g.Key,
              count = g.Count()
            };

            -------------------------------------------
            Linq Method 2:
            -------------------------------------------
            var query = context.People
                   .GroupBy(p => p.name)
                   .Select(g => new { name = g.Key, count = g.Count() });

            

            var productsOfManufactors = (from products in db.Products
                                        group products by products.ManufactorId into manufactor
                                        select new { id = manufactor.Key, count = manufactor.Count() }).ToArray();

            /*
            Type t = productsOfManufactors.GetType();
            //This answer is long overdue for an update for C# 4:
            dynamic d = productsOfManufactors;
            
            ViewBag.productsOfManufactors = productsOfManufactors; 
            
            */

            UpdateTotalProducts();

            return View(db.Manufactors.ToList());
        }

        // GET: Manufactors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufactor manufactor = db.Manufactors.Find(id);
            if (manufactor == null)
            {
                return HttpNotFound();
            }
            return View(manufactor);
        }

    // GET: Manufactors/Search/
    public ActionResult Search(string name, string description, int? totalProduct)
    {
        UpdateTotalProducts();

        var manufactors = (from m in db.Manufactors
                          select m).ToList();
  
        if (!String.IsNullOrEmpty(name))
        {
            manufactors = manufactors.Where(m => m.Name.Contains(name)).ToList();
        }

        if (!String.IsNullOrEmpty(description))
        {
            manufactors = manufactors.Where(m => m.Desciption.Contains(description)).ToList();
        }

        if (totalProduct >= 0)
        {
            manufactors = manufactors.Where(m => m.TotalProduct.Equals(totalProduct)).ToList();
        }

        return View(manufactors);
    }

        // GET: Manufactors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Manufactors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Desciption,Logo")] Manufactor manufactor)
        {
            if (ModelState.IsValid)
            {
                db.Manufactors.Add(manufactor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(manufactor);
        }

        // GET: Manufactors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufactor manufactor = db.Manufactors.Find(id);
            if (manufactor == null)
            {
                return HttpNotFound();
            }
            return View(manufactor);
        }

        // POST: Manufactors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Desciption,Logo")] Manufactor manufactor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manufactor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(manufactor);
        }

        // GET: Manufactors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manufactor manufactor = db.Manufactors.Find(id);
            if (manufactor == null)
            {
                return HttpNotFound();
            }
            return View(manufactor);
        }

        // POST: Manufactors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Manufactor manufactor = db.Manufactors.Find(id);
            db.Manufactors.Remove(manufactor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        protected void UpdateTotalProducts()
        {
            var manufactors = from man in db.Manufactors
                              select man;

            var productsOfManufactors = (from products in db.Products
                                         group products by products.ManufactorId into manufactor
                                         select new { id = manufactor.Key, count = manufactor.Count() }).ToArray();

           foreach(var pom in productsOfManufactors)
            {
                var pomID = pom.GetType().GetProperty("id").GetValue(pom, null);
                var pomCount = pom.GetType().GetProperty("count").GetValue(pom, null);

                Manufactor manufactor = db.Manufactors.Find(pomID);
                manufactor.TotalProduct = (int)pomCount;
            }

            db.SaveChanges();
        }
    }
}

DefenceStore/Views/Manufactors/Create.cshtml
@model DefenceStore.Models.Manufactor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manufactor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DefenceStore/Views/Manufactors/Delete.cshtml
@model DefenceStore.Models.Manufactor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manufactor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desciption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desciption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DefenceStore/Views/Manufactors/Details.cshtml
@model DefenceStore.Models.Manufactor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Manufactor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Desciption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Desciption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalProduct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalProduct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DefenceStore/Views/Manufactors/Edit.cshtml
@model DefenceStore.Models.Manufactor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Manufactor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desciption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desciption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desciption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DefenceStore/Views/Manufactors/Index.cshtml
@model IEnumerable<DefenceStore.Models.Manufactor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Search", "Manufactors", FormMethod.Get))
    {
    <p>
        Name: @Html.TextBox("name")
        Description @Html.TextBox("description")
        @*Number of Products: @Html.TextBox("totalProduct", new { type="number", min="0", max="100" })  *@
        Number of Products: <input type="number" min="0" step="1" name="totalProduct" id="totalProduct" />
        <input type="submit" value="Filter" />
    </p>
    }


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desciption)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalProduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th></th>
        </tr>
        @if (Model.Any())
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Desciption)
                    </td>
                    @*
                        <td>
                            @{
                                var profman = ViewBag.productsOfManufactors[item.ID-1];
                            }
                            @profman.GetType().GetProperty("count").GetValue(profman, null)
                        </td>
                    *@
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalProduct)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Logo)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "edit" })
                        @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "details" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "delete" })
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    No Results Found!
                </td>
            </tr>
        }
    </table>

DefenceStore/Views/Manufactors/Search.cshtml
@model IEnumerable<DefenceStore.Models.Manufactor>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Search", "Manufactors", FormMethod.Get))
    {
        <p>
            Name: @Html.TextBox("name")
            Description @Html.TextBox("description")
            @*Number of Products: @Html.TextBox("totalProduct", new { type="number", min="0", max="100" })  *@
            Number of Products: <input type="number" min="0" step="1" name="totalProduct" id="totalProduct" />
            <input type="submit" value="Filter" />
        </p>
     }


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desciption)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalProduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logo)
            </th>
            <th></th>
        </tr>
    @if (Model.Any())
    { 
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desciption)
                </td>
                @*
                    <td>
                        @{
                            var profman = ViewBag.productsOfManufactors[item.ID-1];
                        }
                        @profman.GetType().GetProperty("count").GetValue(profman, null)
                    </td>
                *@
                <td>
                    @Html.DisplayFor(modelItem => item.TotalProduct)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Logo)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "edit" }) 
                    @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "details" }) 
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "delete" })
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td>
                No Results Found!
            </td>
        </tr>
    }
    </table>